### ISSUE TITLE
Add method which parses command from a string

### ISSUE THREAD

**Issue by DvdGiessen** [DvdGiessen/dbus-app-launcher#3]
To make it easier to execute a command line given as a string without first having to split the string in the calling application, we could add a method that parses a string into a command, arguments, and perhaps even environment variables, similar to how the shell would parse such a command line.

The [shellwords](https://hackage.haskell.org/package/shellwords) package seems to be perfect for this.

This will also help work around the issue noted in #2, namely that there's no easy way to call a DBus method with a StringList argument in the KWin JS API.

**Comment by r0skar** [comment]
I think that makes a lot of sense and (imo) makes the behavior more intuitive. Even the naming of the actions (Exec.Cmd) suggest any "valid" command should work.

**Comment by DvdGiessen** [comment]
I've implemented a first version of it using the mentioned package in the [parse-cmd branch](https://github.com/DvdGiessen/dbus-app-launcher/tree/parse-cmd) ([diff](https://github.com/DvdGiessen/dbus-app-launcher/compare/3e3a388071bf8850886f5914d0eb4ce591f4dd03)). ~It still needs some cleaning up (abstracting reused code into separate functions for readability)~, and I ran into [an issue in shellwords](https://github.com/pbrisbin/hs-shellwords/issues/7) causing it to not parse things correctly, which would be nice to resolve before merging this here.

EDIT: Cleaned up the code a bit ([diff](https://github.com/DvdGiessen/dbus-app-launcher/compare/edffec6a9fff8cd2254371c0777e8af2089576d1)), so now all that's left is integrating the fixes that have been happening in shellwords as well.

**Comment by DvdGiessen** [comment]
I've released [v0.1.1.0](https://github.com/DvdGiessen/dbus-app-launcher/releases/tag/v0.1.1.0) which adds this functionality.
