### ISSUE TITLE
Suggested use of system-wide /usr/share/dbus-1/services/nl.dvdgiessen.dbusapplauncher.service is not recommended.

### ISSUE THREAD

**Issue by erenfro** [DvdGiessen/dbus-app-launcher#5]
I'm recommending the change in documention regarding how to use this to not use:
/usr/share/dbus-1/services/nl.dvdgiessen.dbusapplauncher.service

As this is a path intended for packaged system software's defaults, where:

/etc/dbus-1/services/

Is for System Administrators, and for actual users, where this matters the most in this specific situation:

~/.local/share/dbus-1/services/

Which can be created by the user and the same file placed which overrides any system defined service(s) of the same name in /etc or /usr/share directory paths.

**Comment by DvdGiessen** [comment]
Changed the README in 0e2a3cc27d6e9ac98cf087249ac3dbb3502f1e3e. Thanks!
